from pathlib import Path

import pandas as pd

from src.myh_pipeline.config import METADATA_PATH


SOURCE_METADATA_FILE = METADATA_PATH / "source_files.csv"


def load_source_metadata() -> pd.DataFrame:
    """
    Load source file metadata generated by header detection.
    """
    if not SOURCE_METADATA_FILE.exists():
        raise FileNotFoundError(
            f"Source metadata file not found: {SOURCE_METADATA_FILE}. "
            "Run header detection first."
        )

    metadata_df = pd.read_csv(SOURCE_METADATA_FILE)

    return metadata_df[metadata_df["metadata_status"] == "success"]


def load_excel_from_metadata(record: pd.Series) -> pd.DataFrame | None:
    """
    Load one MYH Excel sheet based on source metadata
    and add source traceability columns.
    """
    file_path = Path(record["file_path"])
    year = int(record["source_year"])
    sheet_name = record["sheet_name"]
    header_row = int(record["detected_header_row"])

    print(f"Loading file: {file_path.name}")

    try:
        df = pd.read_excel(
            file_path,
            sheet_name=sheet_name,
            header=header_row,
        )

        df["source_year"] = year
        df["source_file"] = file_path.name
        df["source_sheet"] = sheet_name

        return df

    except Exception as error:
        print(f"Failed to load {file_path.name}: {error}")
        return None


def load_all_years(years: list[int] | None = None) -> dict[int, pd.DataFrame]:
    """
    Load source files from metadata CSV.

    If years is None, load all successfully detected years.
    """
    metadata_df = load_source_metadata()

    if years is not None:
        metadata_df = metadata_df[metadata_df["source_year"].isin(years)]

    dfs = {}

    for _, record in metadata_df.iterrows():
        year = int(record["source_year"])
        df = load_excel_from_metadata(record)

        if df is not None:
            dfs[year] = df

    return dfs


def check_schema(dfs: dict[int, pd.DataFrame]) -> pd.DataFrame:
    """
    Summarize dataframe shapes and columns
    for quick schema comparison across years.
    """
    schema_df = pd.DataFrame(
        [
            {
                "source_year": year,
                "shape": df.shape,
                "columns": list(df.columns),
            }
            for year, df in dfs.items()
        ]
    )

    return schema_df